Resources:
  MyInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0df435f331839b2d6
      Tags:
        - Key: "Name"
          Value: "MyFirstInstance"